services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./bot-help:/app/help
      - ./bot-temp:/app/temp
      - ./config:/app/config
      - ./db:/app/db
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      OUTPUT: /app/help/help.md
      TEMPDIR: /app/temp

volumes:
  lavaplugins:
